; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30501.0 

	TITLE	C:\Users\BINH\Desktop\ASM\Kuznetsov\???2 ??1\Fact_c\func.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_fact
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _fact
_TEXT	SEGMENT
_r$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
_num$ = 8						; size = 4
_res$ = 12						; size = 4
_fact	PROC						; COMDAT
; File c:\users\binh\desktop\asm\kuznetsov\???2 ??1\fact_c\func.c
; Line 2
	push	ebp
	mov	ebp, esp
	sub	esp, 208				; 000000d0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-208]
	mov	ecx, 52					; 00000034H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 3
	mov	DWORD PTR _r$[ebp], 1
; Line 4
	cmp	DWORD PTR _num$[ebp], 1
	jne	SHORT $LN1@fact
; Line 6
	mov	eax, DWORD PTR _res$[ebp]
	mov	DWORD PTR [eax], 1
; Line 7
	jmp	SHORT $LN2@fact
$LN1@fact:
; Line 10
	lea	eax, DWORD PTR _r$[ebp]
	push	eax
	mov	ecx, DWORD PTR _num$[ebp]
	sub	ecx, 1
	push	ecx
	call	_fact
	add	esp, 8
; Line 11
	mov	eax, DWORD PTR _num$[ebp]
	imul	eax, DWORD PTR _r$[ebp]
	mov	ecx, DWORD PTR _res$[ebp]
	mov	DWORD PTR [ecx], eax
$LN2@fact:
; Line 12
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@fact
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 208				; 000000d0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN6@fact:
	DD	1
	DD	$LN5@fact
$LN5@fact:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN4@fact
$LN4@fact:
	DB	114					; 00000072H
	DB	0
_fact	ENDP
_TEXT	ENDS
END
